# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
        include:
          - os: windows-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11"
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: actions/setup-node@v4
      - name: Install node dependencies
        run: |
          cd wollok_kernel/wollok_ts
          npm install
          cd ../..
      - name: Install Python dependencies
        run: |
          pip install -e ".[test]"
      - name: Test with kernel tester
        run: |
          python -m unittest -v
      - name: Check Kernel
        run: |
          cd $HOME
          jupyter kernelspec list | grep wollok

  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies (necessary to build Python dependencies)
        run: |
          cd wollok_kernel/wollok_ts
          npm install
          cd ../..
      - name: Install Python Dependencies
        run: |
          pip install -e .
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}